version: "3"

services:


  frontend:
    container_name: frontend
    build:
      context: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8080:8080"
    networks:
      - osint-net
    environment:
      - NODE_ENV=development


networks:
  osint-net:
    name: osint-net
